### PR TITLE
Adaption to Dashboard 2.1 and Others

### PR DESCRIPTION
**Pull request by Plypy**
This PR contains:

Dashboard 2.1 needed, EJS to JADE,  app passed by parameter, no globals and etc.

Quiet a lot bug fixes for OAuth2 things.

A functional test  for the OAuth2 authorization procedure, which needed to be run after Dashboard is running.

### CODE REVIEW

**Comment by Plypy** [comment]
This one really took me some amount of time, I've found several interesting bugs during working.

**Comment by Plypy** [comment]
One more thing, if you want to see how 'consent.jade' looks, you can either render it by modfying the source or visit 'http://localhost:3000/oauth/authorize?client_id=***&redirect_uri=***&response_type=code`  refering the client you added, which you can also take the [function retrieveAuthCode](https://github.com/Plypy/openmrs-contrib-id-oauth/blob/master/tests/functional.js#L79) as an example.

**Comment by robbyoconnor** [comment]
@Plypy, You forgot to add the jade file ;)

**Comment by Plypy** [comment]
So sorry, missed this during `rebase` or `reset`.. just added them back

**Comment by robbyoconnor** [comment]
It's all cool :)

**Comment by Plypy** [comment]
Also the current oauth module in production is only at [853ac9d](https://github.com/openmrs/openmrs-contrib-id-oauth/commit/853ac9da42a58d784ab80b1f83ffea00aa886555). 

Thus, though I've solved [ID-32](https://issues.openmrs.org/browse/ID-32?jql=project%20%3D%20ID%20AND%20text%20~%20%22remember%22) long ago, it's yet still not available. We shall deploy it soon.

**Comment by robbyoconnor** [comment]
Tests won't run on my machine I suspect that's an issue with my setup but manual testing worked so I am merging this.

**Pull request merged**
